package:
  name: sotolabmeta
  version: 0.1

requirements:
  run:
    - bokeh ==0.9.0
    - ipython-notebook ==3.2.0
    - matplotlib ==1.4.3
    - pandas ==0.16.2
    - pysentani ==0.2.4
    - seaborn ==0.6.0
    - scipy ==0.15.1
    - xlrd ==0.9.3
